env:
  browser: true
  commonjs: true
  es2021: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
ignorePatterns:
  - index.js
rules:
  max-len:
    - error
    - code: 200
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  new-cap:
    - error
    - properties: false
      capIsNew: false
      newIsCap: true